# use styler to style code
on:
  workflow_dispatch:
  push:
    branches: [main]
name: call-style
jobs:
  call-workflow:
    uses: nmfs-stock-synthesis/workflows/.github/workflows/style-r-code.yml@main
