# Update ss3 executables and bump version and submit as a pull request
# For now, only run this manually (not on a schedule) when we know there are updates to the ss3 binaries.
on:
  workflow_dispatch:
name: call-update-ss3
jobs:
  call-workflow:
    uses: nmfs-stock-synthesis/workflows/.github/workflows/update-ss3-version.yml@main
